### ISSUE TITLE
scope is missing in POST /oauth/token

### ISSUE THREAD

**Issue by diligiant** [jgw96/mammoth-app#67]
in POST /oauth/token, grant_type is set to "authorization_code", code is provided but scope is not.

Per [/oauth/token form-data-parameters](https://docs.joinmastodon.org/methods/oauth/#form-data-parameters),
1. scope default value is "read"
2. when code is provided, scope should be equal to the scope provided in /oauth/authorize. There you provide "read write follow push"

**Comment by diligiant** [comment]
@jgw96 (https://codeberg.org/captainepoch) it's not a bug and I'm sorry : I was following the Mastodon spec. Someone expertly referred me to the [OAuth 2.0 rfc] (https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3) and scope (nor client_secret) should be part of the Access Token Request.

A good reminder for me of where to get authoritative information.

sorry again.

**Comment by jgw96** [comment]
All good 😊
